name: Publish API With Docker Compose

on:
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{secrets.VPS_KEY}}
      VPS_IP: ${{secrets.VPS_IP}}
    steps:
      - name: Setup SSH and Deploy
        run: |
          echo "Teste123"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts

          