name: Publish API With Docker Compose

on:
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{secrets.VPS_KEY}}
      VPS_IP: ${{secrets.VPS_IP}}
    steps:
      - name: Setup SSH and Deploy
        run: |
          echo "Teste123"
          